### ISSUE TITLE
Code is outdated and lacks a license

### ISSUE THREAD

**Issue by makamys** [WhiskyTangoFawks/WTFCavebiomes#5]
This repo contains the source for version ~~1.31~~ 1.54 of the mod. The latest version (for 1.7.10) is 1.6. Can you upload the latest version's source if you still have it?
Also, I suggest adding a license to the mod, since it is currently unclear if we are allowed to make forks of it.

The above issues apply to [WTFCore's repo](https://github.com/WhiskyTangoFawks/WTFCore) too: it has the source for ~~1.51~~ 1.66 while the latest version is 1.7. (I didn't create a separate issue for it because I didn't want to spam your inbox with this.)

**Comment by WhiskyTangoFawks** [comment]
What's here is what I have, I don't have a local dev environment anymore, but the 1.7.0 might be in a different repository on this account. It's been years since I worked on this, and I have since learned a lot about proper use of github.

Forking this probably isn't a great idea though. The minecraft generator recieved a massive overhaul in v1.something or other (14, 15 maybe), the approach I used here I wouldn't recommend anymore.

**Comment by makamys** [comment]
I've already looked at your repos but failed to find what I was looking for (Expedition's repo starts at MC 1.10). I only want to fork the project to fix a bug I found in the 1.7.10 version (and make other small fixes if the need arises).
I managed to decompile the 1.6 version and get it to build. Would I be allowed to distribute it?

**Comment by WhiskyTangoFawks** [comment]
Yes, and good luck. If you need anything, feel free to ask, although it's been a few years since I worked on this, and I am not sure how much I remember.

**Comment by makamys** [comment]
Awesome, thanks.
By the way, I just realized the code in this repo is actually version 1.54, so it wasn't actually as far behind as I thought. It was likely only missing one or two commits.
